version: '3.9'
services:
  mongo:
    image: mongo:4.2.8
  back:
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3000:$PORT
    environment:
      - PORT=$PORT
      - MONGODB_URI=$MONGODB_URI
      - SECRET=$SECRET
