name: ci
on:
  push:
    branches:
      - 'master'
env:
  NAME: express_mongo_boilerplate
  NODE_VERSION: 18.7.0
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Tag
        id: autotagger
        uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: '${{ secrets.GIT_TOKEN }}'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: run tests
        run: docker-compose -f docker-compose.prod.yml run back npm run test
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.NAME }}:${{ steps.autotagger.outputs.tagname }}, ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.NAME }}:latest
